# version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: ${SA_PASSWORD}
      ACCEPT_EULA: "Y"
    volumes:
      - sql_data:/var/opt/mssql

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"     # для сервісів
      - "15672:15672"   # для UI
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"

  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    container_name: azurite
    ports:
      - "10000:10000" # Blob
      - "10001:10001" # Queue
      - "10002:10002" # Table
    volumes:
      - azurite_data:/data
  authservice:
    container_name: authservice
    build:
      context: ./AuthService   # шлях до папки з Dockerfile твого сервісу
      dockerfile: Dockerfile   # якщо Dockerfile має іншу назву - вкажи тут
    ports:
      - "5000:5000"            # прокидаємо порт 5000 з контейнера на хост  
    environment:
      - ASPNETCORE_URLS=http://+:5000
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=AuthDb;User Id=sa;Password=${SA_PASSWORD};TrustServerCertificate=True;
      # додай інші змінні середовища, які потрібні сервісу
    depends_on:
      - sqlserver
      - rabbitmq
      - redis
  gateway:
    container_name: gateway
    build:
      context: ./Gateway.Api
      dockerfile: Dockerfile
    ports:
      - "7000:80"
volumes:
  sql_data:
  azurite_data:
